

services:
  app:
    image: Connectify-backend/my-app:latest  # Your Docker Hub image
    container_name: Connectify-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./logs:/app/logs  # Persist logs on host
    networks:
      - Connectify-ne

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  # For SSL later
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - app
    networks:
      - Connectify-backend

networks:
  Connectify-backend:
    driver: bridge